auto: true
server: true
permalink: none
baseurl: "http://kappataumu.com"
exclude:
- .gitignore
- README.md
prose:
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "nouveau_article"
      - name: "category": 
        field:
          element: "hidden"
          value: "articles"
