markdown: redcarpet
pygments: true

auto: true
server: true
permalink: none
baseurl: "http://kappataumu.com"
exclude:
- .gitignore
- README.md
prose:
  rooturl: "_posts"
  siteurl: "http://kappataumu.com"
  media: "uploads"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "nouveau_article"
      - name: "category" 
        field:
          element: "hidden"
          value: "articles"
      - name: "author"
        field:
          element: "hidden"
          value: "kappataumu"
      - name: "author_twitter"
        field:
          element: "hidden"
          value: "kappataumu"
      - name: "happyness"
        field:
          element: "multiselect"
          label: "Are you happy today?"
          placeholder: "Choose nay or yay"
          options:
            - name: "Yes!"
              value: "on"
            - name: "No..."
              value: "off"
